### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by madhav1ag** [man805/Diffusion-Video-Autoencoders#2]
Hi @man805 
Thanks for releasing the training code. However, there is no inference code available to generate the talking head videos as shown in the paper. Can you share the same as well? It will be very helpful.

**Comment by gmkim-ai** [comment]
Hi, @mdv3101.

Actually, I used CLIP-based editing's example command in github README.md for results in paper. 
If you have any trouble in reproducing, please use this already cropped frames ([link](https://drive.google.com/file/d/1llfrcAe_8TkCNP_cQIZPqRRzPYrKFXm4/view?usp=sharing)).

I didn't understand why, but even if the same command was used, the cropped images through the provided code and the cropped images used previously showed different results.
The link above is a link to the cropped image that was previously used.
These cropped images were made a long time ago, so I don't remember how they cropped.
You will be able to reproduce the paper results with below command.

```
python editing_CLIP.py --attribute "Beard" \
                       --src_txt "face" \
                       --trg_txt "face with beard" \
                       --lr 0.002 \
                       --scale 0.5 \
                       --clip_loss_w 5 \
                       --id_loss_w 1 \
                       --l1_loss_w 5 \
                       --video_path => (LOAD CROPPED IMAGES DIRECTLY IN CODE, NOT THIS WAY)
```
